answer: |
  for raft <- rafts {
      raft.right 7
  }
  up 6
code: |
  for raft <- rafts {
      raft.right 9
  }
  up 6
hint: for loop
layout: |2
       tt     tt
       tt     tt
       tt     tt
       tt     tt
       tt     tt
       tt  s  tt
       tt     tt
  wwTwwwwwwwwwwwwwwwww
  wwTwwwwwwwwwwwwwwwww
  wwTwwwwwwwwwwwwwwwww
       tt     tt
       tt  i  tt
       ttttttttt
successMsg: Bingo, the rafts helps!
