answer: |
  up 6
  right 6
code: |
  up 6
hint: You can not cross water
layout: |2





              s
         ww
          ww
           ww
            ww
             ww
        i
successMsg: Wonderful!
